// Generated by gencpp from file aml_perception/AddTwoIntsResponse.msg
// DO NOT EDIT!


#ifndef AML_PERCEPTION_MESSAGE_ADDTWOINTSRESPONSE_H
#define AML_PERCEPTION_MESSAGE_ADDTWOINTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aml_perception
{
template <class ContainerAllocator>
struct AddTwoIntsResponse_
{
  typedef AddTwoIntsResponse_<ContainerAllocator> Type;

  AddTwoIntsResponse_()
    : ans(0)  {
    }
  AddTwoIntsResponse_(const ContainerAllocator& _alloc)
    : ans(0)  {
  (void)_alloc;
    }



   typedef int64_t _ans_type;
  _ans_type ans;




  typedef boost::shared_ptr< ::aml_perception::AddTwoIntsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aml_perception::AddTwoIntsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddTwoIntsResponse_

typedef ::aml_perception::AddTwoIntsResponse_<std::allocator<void> > AddTwoIntsResponse;

typedef boost::shared_ptr< ::aml_perception::AddTwoIntsResponse > AddTwoIntsResponsePtr;
typedef boost::shared_ptr< ::aml_perception::AddTwoIntsResponse const> AddTwoIntsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aml_perception::AddTwoIntsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aml_perception::AddTwoIntsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aml_perception

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aml_perception::AddTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aml_perception::AddTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aml_perception::AddTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aml_perception::AddTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aml_perception::AddTwoIntsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aml_perception::AddTwoIntsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aml_perception::AddTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "042649983ff391cc0995d4c6af1295cc";
  }

  static const char* value(const ::aml_perception::AddTwoIntsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x042649983ff391ccULL;
  static const uint64_t static_value2 = 0x0995d4c6af1295ccULL;
};

template<class ContainerAllocator>
struct DataType< ::aml_perception::AddTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aml_perception/AddTwoIntsResponse";
  }

  static const char* value(const ::aml_perception::AddTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aml_perception::AddTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 ans\n\
\n\
";
  }

  static const char* value(const ::aml_perception::AddTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aml_perception::AddTwoIntsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ans);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddTwoIntsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aml_perception::AddTwoIntsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aml_perception::AddTwoIntsResponse_<ContainerAllocator>& v)
  {
    s << indent << "ans: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ans);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AML_PERCEPTION_MESSAGE_ADDTWOINTSRESPONSE_H
