// Generated by gencpp from file aml_perception/AddTwoInts.msg
// DO NOT EDIT!


#ifndef AML_PERCEPTION_MESSAGE_ADDTWOINTS_H
#define AML_PERCEPTION_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <aml_perception/AddTwoIntsRequest.h>
#include <aml_perception/AddTwoIntsResponse.h>


namespace aml_perception
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace aml_perception


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aml_perception::AddTwoInts > {
  static const char* value()
  {
    return "72451fc6a0b38b132e2068315b06380a";
  }

  static const char* value(const ::aml_perception::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::aml_perception::AddTwoInts > {
  static const char* value()
  {
    return "aml_perception/AddTwoInts";
  }

  static const char* value(const ::aml_perception::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::aml_perception::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::aml_perception::AddTwoInts > 
template<>
struct MD5Sum< ::aml_perception::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aml_perception::AddTwoInts >::value();
  }
  static const char* value(const ::aml_perception::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aml_perception::AddTwoIntsRequest> should match 
// service_traits::DataType< ::aml_perception::AddTwoInts > 
template<>
struct DataType< ::aml_perception::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::aml_perception::AddTwoInts >::value();
  }
  static const char* value(const ::aml_perception::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aml_perception::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::aml_perception::AddTwoInts > 
template<>
struct MD5Sum< ::aml_perception::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aml_perception::AddTwoInts >::value();
  }
  static const char* value(const ::aml_perception::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aml_perception::AddTwoIntsResponse> should match 
// service_traits::DataType< ::aml_perception::AddTwoInts > 
template<>
struct DataType< ::aml_perception::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::aml_perception::AddTwoInts >::value();
  }
  static const char* value(const ::aml_perception::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AML_PERCEPTION_MESSAGE_ADDTWOINTS_H
